"""add is_active column to all tables

Revision ID: 31dbd40318fe
Revises: 112c7f12f161
Create Date: 2026-08-20 19:54:21.539003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dbd40318fe'
down_revision = '112c7f12f161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
