"""add deleted_at column in order model

Revision ID: 332c418626b6
Revises: 21f6d8e04138
Create Date: 2026-09-03 20:55:09.844878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332c418626b6'
down_revision = '21f6d8e04138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
