"""add payments table

Revision ID: 746a951a0a3e
Revises: 332c418626b6
Create Date: 2026-09-09 03:35:41.693577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746a951a0a3e'
down_revision = '332c418626b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=25), server_default='pending', nullable=False),
    sa.Column('payment_method', sa.String(length=15), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('settlement_time', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'paid', 'expired', 'failed')", name='ck_payments_status_valid'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_payment_order_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
