"""add constraint for users role

Revision ID: 9a308900b370
Revises: 7f3c9a2b1d84
Create Date: 2026-08-23 22:06:45.730911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a308900b370'
down_revision = '7f3c9a2b1d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
        batch_op.create_check_constraint('ck_users_role_valid', "role IN ('buyer', 'seller', 'admin')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role_valid', type_='check')
        batch_op.alter_column('role',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))

    # ### end Alembic commands ###
