"""add role column to user table

Revision ID: e67349ef02fb
Revises: 5cf2a458e34d
Create Date: 2026-08-15 21:38:44.996088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67349ef02fb'
down_revision = '5cf2a458e34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_status_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('orders_total_amount_check'), type_='check')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_price_check'), type_='check')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('role')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('products_price_check'), 'price > 0::numeric')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('orders_total_amount_check'), 'total_amount >= 0::numeric')
        batch_op.create_check_constraint(batch_op.f('orders_status_check'), "status::text = ANY (ARRAY['waitingForPayment'::character varying::text, 'processing'::character varying::text, 'shipped'::character varying::text, 'delivered'::character varying::text, 'cancelled'::character varying::text])")

    # ### end Alembic commands ###
